### PR TITLE
Add mostly automated system preparation

### PR DESCRIPTION
**Pull request by BranislavRistic**
This PR condenses the manual steps for hardware and system setup into a bunch of scripts that can be run once at system setup and should simplify the installation on a RPi.  

Major differences to the current procedure:
* Starts a dedicated X session (does not rely on a running one, i.e. runs on the RPi OS `lite` image)
* CAN interface settings are in `/etc/network/interfaces`: no need to run `resetCAN.sh` anymore
* Installs boot settings to `/boot/firmware` on newer OS versions
* Systemd units in `/etc` instead of `/lib`
   * web service relies on running tessie

* Things to be checked: consistency with rest of README

### CODE REVIEW

**Comment by ursl** [comment]
Hoi Bane, 

I have issues with your PR. I burned a vanilla rpi image using the default versions for the Raspberry Pi 4 Model B Rev 1.1 I have and then I get (after correcting `etc/prepareSystem.sh` to `etc/prepare_system.sh`)

```
pi@coldbox03:~/tessie $ ./etc/prepare_system.sh 
!!!!WARNING!!!!
Run this on a fresh system only. You have 10s to stop by pressing CTRL+C

##########################################
Installing packages

##########################################
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:3 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:4 http://archive.raspberrypi.com/debian bookworm InRelease [23.6 kB]     
Reading package lists... Done      
E: Release file for http://deb.debian.org/debian-security/dists/bookworm-security/InRelease is not valid yet (invalid for another 19d 9h 56min 16s). Updates for this repository will not be applied.
E: Release file for http://deb.debian.org/debian/dists/bookworm-updates/InRelease is not valid yet (invalid for another 19d 16h 53min 9s). Updates for this repository will not be applied.
E: Release file for http://archive.raspberrypi.com/debian/dists/bookworm/InRelease is not valid yet (invalid for another 18d 17h 13min 34s). Updates for this repository will not be applied.
```

Comments?

**Comment by BranislavRistic** [comment]
Hi Urs,
This is a failure of `apt(-get) update`. The problem here is that when you start the RPi for the first time, the date and time on the device are wrong. It takes a minute or two after establishing connection to the internet for the NTP update. Please try to run `apt update` and if it works normally then the script should, too.

**Comment by ursl** [comment]
The next problems: 
- I see `pigpiod` and `tessie-web` in `systemctl status`: 
```
           │ │ └─914 /usr/sbin/ntpd -p /run/ntpd.pid -c /etc/ntpsec/ntp.conf -g -N -u ntpsec:ntpsec
           │ ├─pigpiod.service
           │ │ └─580 /usr/bin/pigpiod -l
           │ ├─polkit.service
           │ │ └─572 /usr/lib/polkit-1/polkitd --no-debug
           │ ├─rtkit-daemon.service
           │ │ └─1041 /usr/libexec/rtkit-daemon
           │ ├─ssh.service
           │ │ └─923 "sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups"
           │ ├─systemd-journald.service
           │ │ └─289 /lib/systemd/systemd-journald
           │ ├─systemd-logind.service
           │ │ └─593 /lib/systemd/systemd-logind
           │ ├─systemd-udevd.service
           │ │ └─udev
           │ │   └─319 /lib/systemd/systemd-udevd
           │ ├─tessie-web.service
           │ │ └─2470 /usr/bin/node server3.js
           │ ├─triggerhappy.service
           │ │ └─602 /usr/sbin/thd --triggers /etc/triggerhappy/triggers.d/ --socket /run/thd.socket --user nobody --deviceglob "/dev/i>
           │ ├─udisks2.service
           │ │ └─605 /usr/libexec/udisks2/udisksd
           │ └─wpa_supplicant.service
           │   └─699 /sbin/wpa_supplicant -u -s -O "DIR=/run/wpa_supplicant GROUP=netdev"
```
but I do not see `tessie`. I can start `tessie` manually, it compiled and is runnable. Comments?

- I can connect to `http://coldbox03:3000`, but not `http://coldbox03`. Please add the `nginx` setup.

**Comment by ursl** [comment]
There is another problem after running your automatized setup: The screen is just white.

**Comment by BranislavRistic** [comment]
Hi Urs,
Thanks a lot for trying it out.

Sure, I can rename the services. It makes, of course, sense to keep it compatible with the current approach. I'll also add nginx once we have solved the other issues.

`tessie` should start as `tessie-server` and the web service should not be running when `tessie` isn't. Do you get a reasonable reading/control via the web interface?

Could you send me the output file of  `sudo bash -xc 'dpkg -l; lsb_release -av; systemctl status; systemctl status tessie-server; systemctl status tessie-web; journalctl -xeu tessie-server; journalctl -xeu tessie-web; dmesg; cat /var/log/Xorg.1.log; cat /var/log/Xorg.0.log' &> debug.out` ?

I'll be back in the lab on Monday and can try to reproduce it on our setup.

**Comment by ursl** [comment]
I think I am not enthusiastic about this PR at the moment. It does not work out of the box with a vanilla system. The unified/automatic  approach  does not help in identifying the underlying issues when something does not work out of the box. I have a fool-proof installation document nearly ready (modulo final line-by-line copy-pasting) -- I agree that the current README.md is not appropriate for general use. I will have a "user guide" ready next week. 

I would link to this scripted procedure (this PR) as a possible alternative.

**Comment by ursl** [comment]
Referenced the branch in the user guide and the readme.

**Pull request closed without merging**
